import type { Metadata } from 'next'
import { Inter, Poor_Story } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] });
const poorStory = Poor_Story({ subsets: ['latin'], weight: ['400',]});

export const metadata: Metadata = {
  title: 'Story of Arda',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poorStory.className}>{children}</body>
    </html>
  )
}
